#!/bin/bash

ETH_MAC_ADDRESS=`ip addr show {{ eth_interface }} | grep link/ether | awk '{ print $2 }'`

echo "Initializing tap0 using {{ eth_interface }} MAC address: ${ETH_MAC_ADDRESS}"

/usr/sbin/openvpn --mktun --dev tap0 --lladdr ${ETH_MAC_ADDRESS} 

echo "Creating Ethernet bridge"

brctl addbr br0

ip link set tap0 up

echo "Adding tap0 to Ethernet bridge"

brctl addif br0 tap0

echo "Setting vpn static ip"

ip a add {{ vpn_client_vpn_ip }}/{{ vpn_server_network_prefix }} brd {{ vpn_server_vpn_broadcast }}  dev br0

ip link set br0 up
