---
###############################
# Check for mandatory variables
###############################

- fail: msg="Variable ca_cert not defined"
  when: ca_cert is undefined

- fail: msg="Variable client_cert not defined"
  when: client_cert is undefined

- fail: msg="Variable client_key not defined"
  when: client_key is undefined

- fail: msg="Variable vpn_server_ip not defined"
  when: vpn_server_ip is undefined

- fail: msg="Variable vpn_server_vpn_ip not defined"
  when: vpn_server_vpn_ip is undefined

- fail: msg="Variable vpn_server_vpn_netmask not defined"
  when: vpn_server_vpn_netmask is undefined

- fail: msg="Variable eth_interface not defined"
  when: eth_interface is undefined

- fail: msg="Variable default_name_server not defined"
  when: default_name_server is undefined

#################
# Install OpenVPN
#################

- name: "Install OpenVPN"
  apt: name=openvpn state=present update_cache=true

- name: "Install resolvconf"
  apt: name=resolvconf state=present

#################
# Copy certificates
#################

- name: "Ensures /etc/openvpn/certs dir exists"
  file: path=/etc/openvpn/certs state=directory mode=700

- name: "Copy CA certificate"
  copy: src=openvpn/{{ ca_cert }} dest=/etc/openvpn/certs/{{ ca_cert }} mode=400
  notify: restart openvpn

- name: "Copy Client certificate"
  copy: src=openvpn/{{ client_cert }} dest=/etc/openvpn/certs/{{ client_cert }} mode=400
  notify: restart openvpn

- name: "Copy Client key"
  copy: src=openvpn/{{ client_key }} dest=/etc/openvpn/certs/{{ client_key }} mode=400

#################
# Copy configuration
#################

- name: "Copy OpenVPN configuration"
  template: src=client.conf dest=/etc/openvpn/client.conf
  notify: restart openvpn

#################
# Enable and start openVPN
#################

- service: name=openvpn enabled=true

- command: systemctl start openvpn@client.service
