---
###############################
# Check for mandatory variables
###############################

- fail: msg="Variable ca_cert not defined"
  when: ca_cert is undefined

- fail: msg="Variable server_cert not defined"
  when: server_cert is undefined

- fail: msg="Variable server_key not defined"
  when: server_key is undefined

- fail: msg="Variable dh_params not defined"
  when: dh_params is undefined

#######################
# Update hosts
#######################

#- name: "Update hosts"
#  template: src=hosts dest=/etc/hosts

#######################
# Enable IP forwarding
#######################

- name: "Enable ip_forward"
  sysctl: name=net.ipv4.ip_forward value=1 state=present

- name: "Accept to forward between interfaces"
  iptables:
      chain: FORWARD
      policy: ACCEPT

- name: "Add nat for openvpn trafffic to internet"
  iptables:
      table: nat
      chain: POSTROUTING
      source: "{{ vpn_network_cidr }}"
      out_interface: "{{ default_interface }}"
      jump: MASQUERADE

#######################
# Install OpenVPN
#######################

- name: "Install OpenVPN"
  apt: name=openvpn state=present

#######################
# Copy certificates
#######################

- name: "Ensures /etc/openvpn/certs dir exists"
  file: path=/etc/openvpn/certs state=directory mode=700

- name: "Copy CA certificate"
  copy: src=openvpn/{{ ca_cert }} dest=/etc/openvpn/certs/{{ ca_cert }} mode=400
  notify: restart openvpn

- name: "Copy Server certificate"
  copy: src=openvpn/{{ server_cert }} dest=/etc/openvpn/certs/{{ server_cert }} mode=400

- name: "Copy Server key"
  copy: src=openvpn/{{ server_key }} dest=/etc/openvpn/certs/{{ server_key }} mode=400

- name: "Copy DH parameters"
  copy: src=openvpn/{{ dh_params }} dest=/etc/openvpn/certs/{{ dh_params }} mode=400

#######################
# Copy configuration
#######################

- name: "Copy OpenVPN configuration"
  template: src=server.conf dest=/etc/openvpn/server.conf

#######################
# Enable and start OpenVPN
#######################

- service: name=openvpn enabled=true

- command: systemctl start openvpn@server.service

